# Generated by Django 6.0.2 on 2026-02-08 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0002_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default=django.utils.timezone.now, help_text='Link do vídeo (YouTube, Vimeo, Panda)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Ordem da aula no curso (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
